// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { MakeAndCreateApiV1WorkflowImportMakeAndCreatePostData, MakeAndCreateApiV1WorkflowImportMakeAndCreatePostErrors, MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponses, MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostData, MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostErrors, MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponses, N8nAndCreateApiV1WorkflowImportN8nAndCreatePostData, N8nAndCreateApiV1WorkflowImportN8nAndCreatePostErrors, N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponses, N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostData, N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostErrors, N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponses, SkillAndCreateApiV1WorkflowImportSkillAndCreatePostData, SkillAndCreateApiV1WorkflowImportSkillAndCreatePostErrors, SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponses, SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostData, SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostErrors, SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponses, ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostData, ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostErrors, ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponses, ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostData, ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostErrors, ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * N8N Packaged Draft
 */
export const n8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPost = <ThrowOnError extends boolean = false>(options: Options<N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostData, ThrowOnError>) => (options.client ?? client).post<N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponses, N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/n8n-packaged-draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * N8N And Create
 */
export const n8nAndCreateApiV1WorkflowImportN8nAndCreatePost = <ThrowOnError extends boolean = false>(options: Options<N8nAndCreateApiV1WorkflowImportN8nAndCreatePostData, ThrowOnError>) => (options.client ?? client).post<N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponses, N8nAndCreateApiV1WorkflowImportN8nAndCreatePostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/n8n-and-create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Make Packaged Draft
 */
export const makePackagedDraftApiV1WorkflowImportMakePackagedDraftPost = <ThrowOnError extends boolean = false>(options: Options<MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostData, ThrowOnError>) => (options.client ?? client).post<MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponses, MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/make-packaged-draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Make And Create
 */
export const makeAndCreateApiV1WorkflowImportMakeAndCreatePost = <ThrowOnError extends boolean = false>(options: Options<MakeAndCreateApiV1WorkflowImportMakeAndCreatePostData, ThrowOnError>) => (options.client ?? client).post<MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponses, MakeAndCreateApiV1WorkflowImportMakeAndCreatePostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/make-and-create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Zapier Packaged Draft
 */
export const zapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPost = <ThrowOnError extends boolean = false>(options: Options<ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostData, ThrowOnError>) => (options.client ?? client).post<ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponses, ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/zapier-packaged-draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Zapier And Create
 */
export const zapierAndCreateApiV1WorkflowImportZapierAndCreatePost = <ThrowOnError extends boolean = false>(options: Options<ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostData, ThrowOnError>) => (options.client ?? client).post<ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponses, ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/zapier-and-create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Skill Packaged Draft
 */
export const skillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPost = <ThrowOnError extends boolean = false>(options: Options<SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostData, ThrowOnError>) => (options.client ?? client).post<SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponses, SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/skill-packaged-draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Skill And Create
 */
export const skillAndCreateApiV1WorkflowImportSkillAndCreatePost = <ThrowOnError extends boolean = false>(options: Options<SkillAndCreateApiV1WorkflowImportSkillAndCreatePostData, ThrowOnError>) => (options.client ?? client).post<SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponses, SkillAndCreateApiV1WorkflowImportSkillAndCreatePostErrors, ThrowOnError>({
    url: '/api/v1/workflow/import/skill-and-create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
