// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | 'https://app.dograh.com' | (string & {});
};

/**
 * CallDispositionCodes
 */
export type CallDispositionCodes = {
    /**
     * Disposition Codes
     */
    disposition_codes?: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MakeImportAndCreateRequest
 */
export type MakeImportAndCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Make Blueprint
     */
    make_blueprint: {
        [key: string]: unknown;
    };
    /**
     * Strict Http Only
     */
    strict_http_only?: boolean;
    /**
     * Emit Route Subflows
     */
    emit_route_subflows?: boolean;
};

/**
 * MakeImportAndCreateResponse
 */
export type MakeImportAndCreateResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Current Definition Id
     */
    current_definition_id: number | null;
    /**
     * Template Context Variables
     */
    template_context_variables?: {
        [key: string]: unknown;
    } | null;
    call_disposition_codes?: CallDispositionCodes | null;
    /**
     * Total Runs
     */
    total_runs?: number | null;
    /**
     * Workflow Configurations
     */
    workflow_configurations?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version Number
     */
    version_number?: number | null;
    /**
     * Version Status
     */
    version_status?: string | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * MakePackagedDraftRequest
 */
export type MakePackagedDraftRequest = {
    /**
     * Make Blueprint
     *
     * Make scenario blueprint JSON.
     */
    make_blueprint: {
        [key: string]: unknown;
    };
    /**
     * Strict Http Only
     */
    strict_http_only?: boolean;
    /**
     * Emit Route Subflows
     */
    emit_route_subflows?: boolean;
};

/**
 * MakePackagedDraftResponse
 */
export type MakePackagedDraftResponse = {
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * N8nImportAndCreateRequest
 */
export type N8nImportAndCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * N8N Export
     */
    n8n_export: {
        [key: string]: unknown;
    } | Array<unknown>;
    /**
     * Strict Http Only
     */
    strict_http_only?: boolean;
    /**
     * Emit Branch Subflows
     */
    emit_branch_subflows?: boolean;
};

/**
 * N8nImportAndCreateResponse
 */
export type N8nImportAndCreateResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Current Definition Id
     */
    current_definition_id: number | null;
    /**
     * Template Context Variables
     */
    template_context_variables?: {
        [key: string]: unknown;
    } | null;
    call_disposition_codes?: CallDispositionCodes | null;
    /**
     * Total Runs
     */
    total_runs?: number | null;
    /**
     * Workflow Configurations
     */
    workflow_configurations?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version Number
     */
    version_number?: number | null;
    /**
     * Version Status
     */
    version_status?: string | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * N8nPackagedDraftRequest
 */
export type N8nPackagedDraftRequest = {
    /**
     * N8N Export
     *
     * Raw n8n export; HTTP Request nodes become tool hints in a linear voice graph.
     */
    n8n_export: {
        [key: string]: unknown;
    } | Array<unknown>;
    /**
     * Strict Http Only
     *
     * When true, reject exports containing non-HTTP nodes.
     */
    strict_http_only?: boolean;
    /**
     * Emit Branch Subflows
     *
     * Map n8n IF/Switch branches to Dograh subflows.
     */
    emit_branch_subflows?: boolean;
};

/**
 * N8nPackagedDraftResponse
 */
export type N8nPackagedDraftResponse = {
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * SkillImportAndCreateRequest
 */
export type SkillImportAndCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Skill Markdown
     */
    skill_markdown: string;
    /**
     * Skill Title
     */
    skill_title?: string | null;
    /**
     * Max Prompt Chars
     */
    max_prompt_chars?: number;
};

/**
 * SkillImportAndCreateResponse
 */
export type SkillImportAndCreateResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Current Definition Id
     */
    current_definition_id: number | null;
    /**
     * Template Context Variables
     */
    template_context_variables?: {
        [key: string]: unknown;
    } | null;
    call_disposition_codes?: CallDispositionCodes | null;
    /**
     * Total Runs
     */
    total_runs?: number | null;
    /**
     * Workflow Configurations
     */
    workflow_configurations?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version Number
     */
    version_number?: number | null;
    /**
     * Version Status
     */
    version_status?: string | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Suggested Template Variables
     */
    suggested_template_variables?: Array<string>;
};

/**
 * SkillPackagedDraftRequest
 */
export type SkillPackagedDraftRequest = {
    /**
     * Skill Markdown
     */
    skill_markdown: string;
    /**
     * Skill Title
     */
    skill_title?: string | null;
    /**
     * Max Prompt Chars
     */
    max_prompt_chars?: number;
};

/**
 * SkillPackagedDraftResponse
 */
export type SkillPackagedDraftResponse = {
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Suggested Template Variables
     */
    suggested_template_variables?: Array<string>;
    /**
     * Agent Prompt Draft
     */
    agent_prompt_draft: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ZapierImportAndCreateRequest
 */
export type ZapierImportAndCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Zapier Export
     */
    zapier_export: {
        [key: string]: unknown;
    };
    /**
     * Strict Http Only
     */
    strict_http_only?: boolean;
    /**
     * Emit Paths Subflows
     */
    emit_paths_subflows?: boolean;
};

/**
 * ZapierImportAndCreateResponse
 */
export type ZapierImportAndCreateResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Current Definition Id
     */
    current_definition_id: number | null;
    /**
     * Template Context Variables
     */
    template_context_variables?: {
        [key: string]: unknown;
    } | null;
    call_disposition_codes?: CallDispositionCodes | null;
    /**
     * Total Runs
     */
    total_runs?: number | null;
    /**
     * Workflow Configurations
     */
    workflow_configurations?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version Number
     */
    version_number?: number | null;
    /**
     * Version Status
     */
    version_status?: string | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * ZapierPackagedDraftRequest
 */
export type ZapierPackagedDraftRequest = {
    /**
     * Zapier Export
     *
     * Zapier import-subset JSON or platform nodes map.
     */
    zapier_export: {
        [key: string]: unknown;
    };
    /**
     * Strict Http Only
     */
    strict_http_only?: boolean;
    /**
     * Emit Paths Subflows
     */
    emit_paths_subflows?: boolean;
};

/**
 * ZapierPackagedDraftResponse
 */
export type ZapierPackagedDraftResponse = {
    /**
     * Workflow Definition
     */
    workflow_definition: {
        [key: string]: unknown;
    };
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

export type N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostData = {
    body: N8nPackagedDraftRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/n8n-packaged-draft';
};

export type N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostError = N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostErrors[keyof N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostErrors];

export type N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponses = {
    /**
     * Successful Response
     */
    200: N8nPackagedDraftResponse;
};

export type N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponse = N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponses[keyof N8nPackagedDraftApiV1WorkflowImportN8nPackagedDraftPostResponses];

export type N8nAndCreateApiV1WorkflowImportN8nAndCreatePostData = {
    body: N8nImportAndCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/n8n-and-create';
};

export type N8nAndCreateApiV1WorkflowImportN8nAndCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type N8nAndCreateApiV1WorkflowImportN8nAndCreatePostError = N8nAndCreateApiV1WorkflowImportN8nAndCreatePostErrors[keyof N8nAndCreateApiV1WorkflowImportN8nAndCreatePostErrors];

export type N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponses = {
    /**
     * Successful Response
     */
    200: N8nImportAndCreateResponse;
};

export type N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponse = N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponses[keyof N8nAndCreateApiV1WorkflowImportN8nAndCreatePostResponses];

export type MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostData = {
    body: MakePackagedDraftRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/make-packaged-draft';
};

export type MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostError = MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostErrors[keyof MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostErrors];

export type MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponses = {
    /**
     * Successful Response
     */
    200: MakePackagedDraftResponse;
};

export type MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponse = MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponses[keyof MakePackagedDraftApiV1WorkflowImportMakePackagedDraftPostResponses];

export type MakeAndCreateApiV1WorkflowImportMakeAndCreatePostData = {
    body: MakeImportAndCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/make-and-create';
};

export type MakeAndCreateApiV1WorkflowImportMakeAndCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeAndCreateApiV1WorkflowImportMakeAndCreatePostError = MakeAndCreateApiV1WorkflowImportMakeAndCreatePostErrors[keyof MakeAndCreateApiV1WorkflowImportMakeAndCreatePostErrors];

export type MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponses = {
    /**
     * Successful Response
     */
    200: MakeImportAndCreateResponse;
};

export type MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponse = MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponses[keyof MakeAndCreateApiV1WorkflowImportMakeAndCreatePostResponses];

export type ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostData = {
    body: ZapierPackagedDraftRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/zapier-packaged-draft';
};

export type ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostError = ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostErrors[keyof ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostErrors];

export type ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponses = {
    /**
     * Successful Response
     */
    200: ZapierPackagedDraftResponse;
};

export type ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponse = ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponses[keyof ZapierPackagedDraftApiV1WorkflowImportZapierPackagedDraftPostResponses];

export type ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostData = {
    body: ZapierImportAndCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/zapier-and-create';
};

export type ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostError = ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostErrors[keyof ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostErrors];

export type ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponses = {
    /**
     * Successful Response
     */
    200: ZapierImportAndCreateResponse;
};

export type ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponse = ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponses[keyof ZapierAndCreateApiV1WorkflowImportZapierAndCreatePostResponses];

export type SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostData = {
    body: SkillPackagedDraftRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/skill-packaged-draft';
};

export type SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostError = SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostErrors[keyof SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostErrors];

export type SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponses = {
    /**
     * Successful Response
     */
    200: SkillPackagedDraftResponse;
};

export type SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponse = SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponses[keyof SkillPackagedDraftApiV1WorkflowImportSkillPackagedDraftPostResponses];

export type SkillAndCreateApiV1WorkflowImportSkillAndCreatePostData = {
    body: SkillImportAndCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflow/import/skill-and-create';
};

export type SkillAndCreateApiV1WorkflowImportSkillAndCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillAndCreateApiV1WorkflowImportSkillAndCreatePostError = SkillAndCreateApiV1WorkflowImportSkillAndCreatePostErrors[keyof SkillAndCreateApiV1WorkflowImportSkillAndCreatePostErrors];

export type SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponses = {
    /**
     * Successful Response
     */
    200: SkillImportAndCreateResponse;
};

export type SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponse = SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponses[keyof SkillAndCreateApiV1WorkflowImportSkillAndCreatePostResponses];
